// <auto-generated />
using System;
using Destiny.ScrimTracker.Logic.Adapters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Destiny.ScrimTracker.App.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200128064418_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.Guardian", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("EloModifier")
                        .HasColumnType("integer");

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LifetimeDeaths")
                        .HasColumnType("integer");

                    b.Property<int>("LifetimeKills")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GamerTag")
                        .IsUnique();

                    b.ToTable("guardians","scrims_tracker");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.GuardianEfficiency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GuardianId")
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<double>("NewEfficiency")
                        .HasColumnType("double precision");

                    b.Property<double>("PreviousEfficiency")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.ToTable("guardian_efficiencies","scrims_tracker");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.GuardianElo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GuardianId")
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<double>("NewElo")
                        .HasColumnType("double precision");

                    b.Property<double>("PreviousElo")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GuardianId");

                    b.ToTable("guardian_elos","scrims_tracker");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.GuardianMatchResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<double>("Efficiency")
                        .HasColumnType("double precision");

                    b.Property<string>("GuardianId")
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .HasColumnType("text");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<string>("MatchTeamId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchTeamId");

                    b.ToTable("guardian_match_results","scrims_tracker");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.Match", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("MatchType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("matches","scrims_tracker");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.MatchTeam", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TeamScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("match_teams","scrims_tracker");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.GuardianEfficiency", b =>
                {
                    b.HasOne("Destiny.ScrimTracker.Logic.Models.Guardian", null)
                        .WithMany()
                        .HasForeignKey("GuardianId");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.GuardianElo", b =>
                {
                    b.HasOne("Destiny.ScrimTracker.Logic.Models.Guardian", null)
                        .WithMany()
                        .HasForeignKey("GuardianId");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.GuardianMatchResult", b =>
                {
                    b.HasOne("Destiny.ScrimTracker.Logic.Models.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId");

                    b.HasOne("Destiny.ScrimTracker.Logic.Models.MatchTeam", null)
                        .WithMany()
                        .HasForeignKey("MatchTeamId");
                });

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.MatchTeam", b =>
                {
                    b.HasOne("Destiny.ScrimTracker.Logic.Models.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId");
                });
#pragma warning restore 612, 618
        }
    }
}
