// <auto-generated />
using Destiny.ScrimTracker.Logic.Adapters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Destiny.ScrimTracker.Api.Migrations
{
    [DbContext(typeof(GuardianContext))]
    [Migration("20200103044723_AddUniqueContraintToGamerTag")]
    partial class AddUniqueContraintToGamerTag
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Destiny.ScrimTracker.Logic.Models.Guardian", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LifetimeDeaths")
                        .HasColumnType("integer");

                    b.Property<int>("LifetimeKills")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GamerTag")
                        .IsUnique();

                    b.ToTable("guardians","scrims_tracker");
                });
#pragma warning restore 612, 618
        }
    }
}
